### PR TITLE
Use pagination on the full package list

### PR DESCRIPTION
**Pull request by s-ludwig**
This is an intermediate step to improve loading performance and bandwidth use of the registry home page. This will later be replaced by different top ten lists.

### CODE REVIEW

**Comment by wilzbach** [comment]
I think we seriously need to improve the stylesheet of the pagination list:

image

**Comment by s-ludwig** [comment]
Outdated CSS in cache? This is how it looks for me:
image

**Comment by wilzbach** [comment]
> Outdated CSS in cache? This is how it looks for me:

Oh sorry - yeah it might be good to avoid this for other users as well by generating a hash-summed CSS file during a build.

**Comment by wilzbach** [comment]
> it might be good to avoid this for other users as well by generating a hash-summed CSS file during a build.

I opened an issue, s.t. it doesn't get forgotten:

https://github.com/dlang/dub-registry/issues/210

**Pull request merged**
