### PR TITLE
Change categories icons with font icons

### PR DESCRIPTION
**Pull request by WebFreak001**
New design:

Blue icons are packages tagged as application

### CODE REVIEW

**Comment by WebFreak001** [comment]
bump @s-ludwig @wilzbach

**Comment by MartinNowak** [comment]
Nice!
I'm hoping to replace the hardly usable/useful categories with tags at some point. Any idea how that would work for tags?

**Comment by WebFreak001** [comment]
tags is a good idea, I would redesign it a bit to have some tags associated with icons and have the first tag with icon be the small icon of a package. It should show at least a few tags in the package listing

**Comment by MartinNowak** [comment]
Yes, integration with a free-form search box is a bit tricky, but solvable.

**Pull request merged**
