### PR TITLE
time to display score

### PR DESCRIPTION
**Pull request by MartinNowak**
- already affects search results
- we get no feedback/improvement ideas while score remains hidden
=> time to lift the curtains

### CODE REVIEW

**Comment by s-ludwig** [comment]
We should give this metric a semantic name, the generic "rating" currently doesn't give a clue what it actually means. What about "relevancy"?

**Comment by WebFreak001** [comment]
uh what unit is this even supposed to be, my most downloaded and one of my most useful packages has a rating of 1.8

**Comment by s-ludwig** [comment]
It's in the range of zero to five (a 5-star rating was the initial idea).

**Comment by MartinNowak** [comment]
Fairly straightforward, balancing a couple of features against the average.
https://github.com/dlang/dub-registry/blob/6e4724067693bab226894435fe4538beca289957/source/dubregistry/registry.d#L575-L617

> uh what unit is this even supposed to be, my most downloaded and one of my most useful packages has a rating of 1.8

Which one?

**Comment by WebFreak001** [comment]
@MartinNowak https://github.com/WebFreak001/FSWatch

**Comment by MartinNowak** [comment]
> @MartinNowak https://github.com/WebFreak001/FSWatch

@WebFreak001 while 10K downloads is quite a lot, there were only 11 downloads in the past month (30 days) which are relevant for the rating.

**Comment by MartinNowak** [comment]
Ready from my side @s-ludwig.
Starting with the migrated data but an old mirror seems to work (just tested), as the score is recomputed on startup. Please still let us know before you're deploying this (e.g. via Slack). FYI @wilzbach

**Comment by s-ludwig** [comment]
Looks good now!

**Pull request merged**
