### PR TITLE
New layout of package page

### PR DESCRIPTION
**Pull request by ohdatboi**
I wanted to add some usefull little things like download statistics or stars, but realised that there is no place where I can put them.

So, I did this:
All package information moved to sidebar at right of the screen. On the small screens (<54em) it showed at the bottom of page. Package name, description, installation instructions and readme stays at left of the screen.
Also, sidebar is grey(gray?) and contains a lot of empty space, so it won't look heavy.

Anyway, it's not done yet
## TODO
- [x] On big screens looks ugly
- [x] Link to page of all versions in `Versions:` section
- [x] 'Versions:' section should also contain date of every version (Looks like a lot of work on backend)

### CODE REVIEW

**Comment by ohdatboi** [comment]
I added 'packages/:packname/versions' page, which shows all versions of package:
beautiful updated fullhd versions
And fixed some issues on package page. It looks like this:
beautiful updated fullhd

**Comment by ohdatboi** [comment]
Ping @s-ludwig @MartinNowak

**Comment by s-ludwig** [comment]
Looks like a good step forward! Things that I noticed:

- There are two regressions in sub package handling: Sub package descriptions are not displayed anymore, and on sub package pages the root package link has been removed. Sub package pages are not linked from anywhere else, so this is not a big deal, but displaying the description, if any, somewhere would be good to keep (vibe-d for example has descriptions).

- The full version list uses up a large amount of vertical space without a practical benefit. Maybe, also to let it blend in better with the rest of the page, putting this into a table (Version/Date) would be a viable alternative.

- For most of the information on the right side it should be okay to move it to the bottom for narrow displays. Just the version number should be kept at the top of the page, especially if a certain version has been selected.

**Comment by ohdatboi** [comment]
>  Just the version number should be kept at the top of the page, especially if a certain version has been selected

Yup, it looks much better. 
version

> Sub package descriptions are not displayed anymore

Okay, it can be displayed like this:
```
subpack1    description
subpack2    description
...
```
Or like this if there is no descriprions:
```
subpack1, subpack2, ...
```

>  sub package pages the root package link has been removed

version
`gtk-d` is the link. I just removed underlining, because it looks ugly.

> Maybe, also to let it blend in better with the rest of the page, putting this into a table (Version/Date) would be a viable alternative.

Indeed. It can be prettier. Let's see what I can do.

**Comment by s-ludwig** [comment]
Looking good, especially with the sub package suffix. How does it look for normal packages? Could it make sense to maybe color the badge black or gray, so that there is not too much red at once in that case?

BTW, sorry for introducing merge conflicts in the meantime. AFAICS it's just adding gitlab URL support to `view_package.dt` and `getPackageInfo` returning `PackageInfo` instead of `Json` (the `Json` is available as the `.info` field of `PackageInfo`).

**Comment by ohdatboi** [comment]
> Looking good, especially with the sub package suffix. How does it look for normal packages? 

Like this:
version_samplepack

> Could it make sense to maybe color the badge black or gray, so that there is not too much red at once in that case?

What about `#ADADAD`?
version_badge_coloured

> BTW, sorry for introducing merge conflicts in the meantime
It's okay. I'll fix conflicts as soon as I finish other things.

**Comment by s-ludwig** [comment]
Okay, great... of course (didn't realize that it wouldn't be a link anymore and would naturally be black). So then red is fine by me!

**Comment by ohdatboi** [comment]
> Sub package descriptions are not displayed anymore

Well, there is no place for this on the sidebar. What if I put them after root package description?

**Comment by ohdatboi** [comment]
- I fixed versions page (Now displayed as table)
- Sub packages now displayed as links (just like dependencies)
- I solved merge conflicts
- Little fixes here and there

**Comment by s-ludwig** [comment]
>> Sub package descriptions are not displayed anymore

> Well, there is no place for this on the sidebar. What if I put them after root package description?

I'm a little bit undecided on this. Maybe it's okay to just let them be links to their corresponding sub package pages after all. On the other hand, they should be listed somewhat prominently and distinctively, because they are central to the usage of some libraries (e.g. arsd-official, but even temporarily for vibe.d).

A possibility could be to combine this with the usage instructions similar to "To use this package, put (...) There are also several sub packages that can be used individually: (list of sub packages with links to their page)".

**Comment by ohdatboi** [comment]
> A possibility could be to combine this with the usage instructions similar to "To use this package, put (...) There are also several sub packages that can be used individually: (list of sub packages with links to their page)".

Good idea.
subpacks-sample
It shows only sub packages with descriptions.

**Comment by s-ludwig** [comment]
Looks good to go from my side. Any additional thoughts, @MartinNowak, @wilzbach, @CyberShadow?

**Comment by wilzbach** [comment]
> Any additional thoughts, @MartinNowak, @wilzbach, @CyberShadow?

First of all (OT),  when I tried to test this locally (on ArchLinux), I had to merge these two PRs locally:

https://github.com/rejectedsoftware/vibe.d/pull/1767
https://github.com/rejectedsoftware/vibe.d/pull/1769

Other distro might want to upgrade to OpenSSL 1.1 in the future as well...
I think @WebFreak001 also had these issues with https://github.com/dlang/dub-registry/pull/211
(`VibeNoSSL` doesn't work because the HTTP client makes SSL requests).

------------------

As you know, I am not a designer, so I can only comment on the big picture (aka end result).
I also think that this is a __huge__ step forward and that it looks pretty amazing. Excellent work!

I tried it out locally with the mirrormode (hence stats and - for some reason I will look into later - the README aren't available) and looks really clean:

image

> I added 'packages/:packname/versions' page, which shows all versions of package.

Nice idea, but it's not linked from the package page anymore. Any specific reason?

> On the small screens (<54em) it showed at the bottom of page.

Hmm, I would at least move important items (like e.g. the author etc.) up to the bottom.
Also it seems that the left alignment isn't perfect for mobile devices:

image

**Comment by s-ludwig** [comment]
>> I added 'packages/:packname/versions' page, which shows all versions of package.
>
> Nice idea, but it's not linked from the package page anymore. Any specific reason?

Isn't that the "Show all 28 versions" link?

**Comment by ohdatboi** [comment]
> Also it seems that the left alignment isn't perfect for mobile devices:

Fixed.

> Hmm, I would at least move important items (like e.g. the author etc.) up to the bottom.

Package can have not just one but a lot of authors. So, `Authors:` field can be very long and take a lot of space, which is ok on large screens, but not-ok on small ones.

**Comment by WebFreak001** [comment]
I can't try this myself because I can't get vibe.d to link and the patches @wilzbach sent didn't fix anything for me but from the screenshot he sent there, I have a minor complaint/suggestion that the margin-top of the left box (above the header) should be the same as the right box:

**Comment by ohdatboi** [comment]
@WebFreak001 Fixed
fixed-top-margin

**Comment by skoppe** [comment]
This is great! Nice work.

**Comment by wilzbach** [comment]
> I can't try this myself because I can't get vibe.d to link and the patches @wilzbach sent didn't fix anything

In what error did you run into? Did you add these two lines to the `dub.sdl`?

```sdl
versions "Have_botan"
dependency "botan" version="~>1.12.0"
```

To ease the convenience of other readers who want to try out the new layout, I uploaded it on the alpha-Server:

http://alpha.dub.pm

(deployed commit is 23e90c7a922057443eb73ec24c5f7c3a7a4ee58c)

OT: During deployment I ran into a segfault with Botan when compiled with LDC. I will try to dig a bit deeper into this, but this definitely shows that we need a better CI system (see e.g. https://github.com/dlang/dub-registry/issues/213).

**Comment by s-ludwig** [comment]
Some last observations from me:
- Was the indentation change of the heading intentional?
- There is a space missing after "System dependencies:"
- Do we still need the sub packages listed on the right side?

**Comment by ohdatboi** [comment]
1. I added padding for the main div (which contains readme and installation instructions), so it will look good ‎ on small screens. Maybe something gone wrong with heading. I'll check it later.2. I'll fix it.3. Yes, we are. Every sub package is listed on the sidebar. Only s‎ub packages with descriptions are listed after installation instructions. So, on the left we have descriptions of sub packages and on the right we have all sub packages.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Sönke LudwigSent: pondelok, 29. mája 2017 11:02To: dlang/dub-registryReply To: dlang/dub-registryCc: Anton Fediushin; AuthorSubject: Re: [dlang/dub-registry] New layout of package page (#203)Some last observations from me:

Was the indentation change of the heading intentional?
There is a space missing after "System dependencies:"
Do we still need the sub packages listed on the right side?


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dlang/dub-registry","title":"dlang/dub-registry","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dlang/dub-registry"}},"updates":{"snippets":[{"icon":"PERSON","message":"@s-ludwig in #203: Some last observations from me:\r\n- Was the indentation change of the heading intentional?\r\n- There is a space missing after \"System dependencies:\"\r\n- Do we still need the sub packages listed on the right side?"}],"action":{"name":"View Pull Request","url":"https://github.com/dlang/dub-registry/pull/203#issuecomment-304611403"}}}

**Comment by ohdatboi** [comment]
Yep, heading indentation was broken. I fixed it.
Also, I moved 'System dependencies' to the bottom.

**Comment by s-ludwig** [comment]
Okay, thanks! From my side, we can merge this after a squash+rebase.

**Comment by WebFreak001** [comment]
I still got a few improvement suggestions because only now I saw the beta link there:



versions don't always align with the dates, try putting it in a table without borders instead of spans with margin.

https://i.webfreak.org/fA9Nns

I would add icons to the left of these values because that is more intuitive than just values. (FontAwesome or Material Design Icons for example)

https://i.webfreak.org/fA9orG

the headers/names of the sections are bold in the upper 3 ones but versions and stats aren't, I think it would look more consistent if you made those bold too.

https://i.webfreak.org/fAT43G

I think a few pixels more bottom margin below the caption would look better (so it looks the same as the left margin from the bottom line of the g, not the text baseline.

https://i.webfreak.org/fATBts

it would be cool if the package name (`dlangui:` in this case) could have a bit less opacity (50% maybe) so it's easier to scan

**Comment by ohdatboi** [comment]
@s-ludwig done!

**Comment by s-ludwig** [comment]
@WebFreak001 Agree to these suggestions. However, I generally wouldn't mind making this an incremental process in which the bulk of the improvements gets merged and successive PRs improve the optical details.

**Comment by ohdatboi** [comment]
> Actually I just noticed that that is the description of the package, adding left margin to that so it fits with the name would be nice.

`git pull`, please. I already fixed this.

> it would be cool if the package name (dlangui: in this case) could have a bit less opacity (50% maybe) so it's easier to scan

Nice idea! I can do it.

> versions don't always align with the dates, try putting it in a table without borders instead of spans with margin and probably put the date first so big whitespaces don't happen.

I'll try it.

> I would add icons + tooltips to the left of these values because that is more intuitive than just values. (FontAwesome or Material Design Icons for example)

I don't think that links should have those. Because simpler is better and links are simple enough - they are red. Red means 'Click me!'.
Also, I think that package creators should not set "homepage" same as their repository link.

I would like to add some badges (like OSI-approved, etc) to licenses and provide links to texts, but it is impossible because of dub. Dub allows you to write anything in 'license' field. 

> (FontAwesome or Material Design Icons for example)

I can't use icons for 3 things on the page. I have to use them for everything or don't use them at all.

> the headers/names of the sections are bold in the upper 3 ones but versions and stats aren't, I think it would look more consistent if you made those bold too.

Oops! I'll fix it.

@s-ludwig +1. A lot of small PRs are better than big one.

**Comment by ohdatboi** [comment]
All right! I fixed everything.

**Comment by s-ludwig** [comment]
Thanks again! Merging.

**Comment by s-ludwig** [comment]
Finally got around to deploy the changes to code.dlang.org now.

**Pull request merged**
