### PR TITLE
Bump dmd to 2.092.1

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by Geod24** [comment]
Can't we compile with LDC ?

**Comment by wilzbach** [comment]
> Can't we compile with LDC ?

Considering that this is still failing on Heroku, we have to.

**Comment by Geod24** [comment]
I don't see it in my apps BTW

**Comment by WebFreak001** [comment]
if the issue is something like
vibe.d build issues
then you can fix it by running
`rm **/dub.selections.json` before building

**Pull request merged**
