### PR TITLE
New layout of 'Add package' page

### PR DESCRIPTION
**Pull request by ohdatboi**
This PR changes layout of the 'Add package' page. I wanted to make it mobile-friendly and clear.

### Screenshots:
big
big_error
small

### CODE REVIEW

**Comment by wilzbach** [comment]
Btw @ohdatboi if you prefer to use a CSS preprocessor (or a CSS library), don't be afraid to propose it here.
The CSS of the dub-registry just used to be quite small and thus manageable by hand.
See also: https://github.com/dlang/dub-registry/issues/210

**Comment by ohdatboi** [comment]
@wilzbach I would like to use CSS preprocessor. There are a lot of obsolete rules wich forces me to overuse `!important` and duplicate functionality that already exists, but I change CSS very frequently and use of preprocessor will make everything even more complex.
So, CSS should be rewrited in future, but it's better not to mess with it right now.

**Comment by s-ludwig** [comment]
Just one request: The page content should generally left align with the header (Ideally with the "D" of DUB, but that seems to have been broken some time ago).

**Comment by ohdatboi** [comment]
> The page content should generally left align

Done.

> Ideally with the "D" of DUB, but that seems to have been broken some time ago

It's now aligned to the left of the `#content`, so it will be fixed as soon as somebody fixes `#content`'s margins.

**Comment by s-ludwig** [comment]
Okay, thanks!

**Pull request merged**
