### PR TITLE
Change the license to Boost

### PR DESCRIPTION
**Pull request by wilzbach**
From https://github.com/dlang/dub/issues/1349

> Thanks for the info. I am not sure whether these commercial companies will look into the source code because dub registry is under GPL license. Maybe you can check whether dub registry could change the license?

CC @s-ludwig @MartinNowak @ohdatboi @ColdenCullen @WebFreak001 @brad-anderson @mdondorff @Kripth @JakobOvrum - are you all okay with this?

--- edit:

The GPL license was added to the `dub.sdl` in this commit: https://github.com/dlang/dub-registry/commit/cc08b3509c3107f1d563b69db3d33c0695b35475 and the LICENSE.txt in this commit https://github.com/dlang/dub-registry/commit/70499db0f9e8eed7cabb36e03d04ccb44f53e105

### CODE REVIEW

**Comment by ColdenCullen** [comment]
This is fine by me! I personally am a huge fan of the Boost license.

**Comment by s-ludwig** [comment]
Still missing @MartinNowak, @brad-anderson, @mdondorff, @Kripth, and @JakobOvrum.

**Comment by brad-anderson** [comment]
I hereby authorize my typo fixes to be relicensed under the Boost license 😜

**Comment by mdondorff** [comment]
I authorize, thanks!

**Comment by Kripth** [comment]
I do authorise my changes to be relicensed.

**Comment by s-ludwig** [comment]
@MartinNowak can we assume that you agree, too? Looking at the log, the changes by @JakobOvrum look like they are not subject to copyright issues, so it should be safe to continue in that case.

**Comment by MartinNowak** [comment]
Fine with me.

**Comment by WalterBright** [comment]
Thank you everyone! This is good news indeed.

**Pull request merged**
