### PR TITLE
Update dependencies to avoid BuildOption fails

### PR DESCRIPTION
**Pull request by ljmf00**
This fixes the issue for publishing an app using new dub `buildOptions` flags such as `betterC` flag, according to the documentation: https://dub.pm/package-format-json.html#build-options .

I noticed that when I added a new package to the registry and got this error:
image

Steps to reproduce:
1. Create a package with `"buildOptions": ["betterC"]`
2. Try to publish into the registry.

**Workarround:** use `"dflags": ["-betterC"]` on your dub config.

### CODE REVIEW

**Comment by ljmf00** [comment]
> Please see [CONTRIBUTING.md](https://github.com/dlang/dub-registry/blob/master/CONTRIBUTING.md) for more information.

Thank you little @dlang-bot . Noticed now that dlang/dub-registry doesn't have a [CONTRIBUTING.md](https://github.com/dlang/dub-registry/blob/master/CONTRIBUTING.md) file! :smiley:

**Comment by ZombineDev** [comment]
Thanks @ljmf00! @s-ludwig @wilzbach good to go?

**Comment by wilzbach** [comment]
Though at the moment only @s-ludwig can do deploys.

**Comment by wilzbach** [comment]
(The failure of the botan builds is unrelated)

**Comment by s-ludwig** [comment]
Deployed current master.

**Pull request merged**
